### ISSUE TITLE
(releases/v1.6) Users not in voice can skip tracks.

### ISSUE THREAD

**Issue by DigitallyFidget** [robinfriedli/aiode#138]
Here's a quality of life issue that was just encountered by a user in my discord. Apparently a track was skipped by another user who was not within the voice channel. I haven't further investigated this myself, but it seems there's perhaps not a check to verify if a user interacting with the reactions is in voice channel.

**Comment by robinfriedli** [comment]
I decided against that restriction because people outside the voice chat using these comands is a valid use case. I could add a guild property and a command interceptor to optionally enable that behavior for botify 2. Alternatively the same bevior may be achieved using custom scripted command interceptors in botify 2, although they do not get triggered by widget actions / reactions.

I am curious about your use case. I presume this is to stop trolling / unwanted input? In that case, couldn't those users just join the voice channel and run those commands anyway? Or if they do not have access to the voice channel, couldn't you just also deny them access from the text channel where you use the bot? Alternatively you could also setup botify permissions to stop untrusted users from using those commands (including reactions) altogether.

The aforementioned property might well be a feature I'll add to botify 2, sounds useful and should be easy to implement.
