### ISSUE TITLE
Youtube API Quota limit

### ISSUE THREAD

**Issue by tristanvann** [robinfriedli/aiode#261]
It seems the YT api has a query limit where the bot stops playing music after around 100 songs or so. Apparently this counts Spotify playlists loaded, even if it hasn't gotten to all songs (aka, when I load a playlist with 10 songs, it counts the full amount against my API usage immediately). This means if I try to load a very large Spotify playlist (hundreds of tracks), it immediately errors out and shuts me out for the entire rest of the day. Currently I have to manually tell Botify to play each track one by one to avoid this.

Is there a way to not perform the YouTube lookup until the song actually is set to play? As in, have botify load the Spotify list, handle the shuffle, queue, etc. on the server but only search YouTube for the song when each song plays?

**Comment by tristanvann** [comment]
Ok just now when I loaded a Spotify playlist it only used 144 units after starting the second song, which seems closer to correct. No idea why last night I loaded one and it instantly maxed it and the API dash showed 10,000 (the max). Confused now

**Comment by robinfriedli** [comment]
Was it the same playlist? Because the results are stored in the spotify_redirect_index table, the same tracks are not looked up multiple times. It does look up the entire playlist, which is something I plan to change, using batches of 50 instead. Have you set the property `YOUTUBE_API_DAILY_QUOTA` (`botify.preferences.youtube_api_daily_quota` for botify 2) to your limit of 10000? It will limit usage of the API by using lavaplayer to crawl the html pages instead when getting close to the limit.

**Comment by tristanvann** [comment]
Ahh, ok. So currently until using batches of 50, it sounds like I should still limit the size of playlists I feed into Botify, so it doesn't get immediately get overloaded.

**Comment by robinfriedli** [comment]
Again, shouldn't be much of a problem if you've set the property and if you've already played the playlist before
