### ISSUE TITLE
Aiode Remove from Playlist Error

### ISSUE THREAD

**Issue by KittyCatCrunchie** [robinfriedli/aiode#332]
Hey :) I'm pretty sure this is a glitch but I might just be inept. I accidentally added a song to a playlist via aiode twice and am trying to remove one of them. I'm using "/remove from: <playlist name> input: <song name>" and that works fine, outputting: 
"Several options found.
Choose an option using the answer command: @aiode answer KEY (replace KEY with the key for your option). Depending on the command you may select several options comma separated.
Key - Option
0 - song by artist (12)
1 - song by artist (29)
all - All of the above"
But when I follow the instruction and input "@aiode answer 0" or the same for 1, it displays this instead of removing the song: "Exception
IllegalArgumentException: Removing a detached instance net.robinfriedli.aiode.entities.Song#749884
CommandContext ID
53c9f668-7260-40e8-9575-a4cebad61ef4"

Again idk if I'm just being exceedingly stupid or if this is a legit glitch. Thanks :)

**Comment by robinfriedli** [comment]
Looks like this is a bug with how the answer command interacts with the remove command. The entities are loaded in the session of the remove command and the answer command then attempts to delete the detached entities in its own session. This likely no longer works since aiode 2 moved to spring boot, thus bootstrapping hibernate via JPA, but used to work with the original hibernate behaviour which iirc allows deleting detached instances. Not a big deal, just means those entities need to get reloaded into the new session now.

**Comment by KittyCatCrunchie** [comment]
Oh okay, should I do anything or...?

Le dim. 16 oct. 2022, 02:37, Robin Friedli ***@***.***> a
écrit :

**Comment by robinfriedli** [comment]
Do you self-host? If so, please check out the latest changes and try again. Or are you on the public instance?

**Comment by KittyCatCrunchie** [comment]
Public I assume, it's not my server.

Le dim. 16 oct. 2022, 16:32, Robin Friedli ***@***.***> a
écrit :

**Comment by robinfriedli** [comment]
I deployed the fix to the public instance, you can try again
