### ISSUE TITLE
[BUG] jda-nas dependency failure

### ISSUE THREAD

**Issue by irishgordo** [robinfriedli/aiode#334]
We currently can't build the project due to a dependency failure of https://github.com/sedmelluq/jda-nas .
It looks like v1.1.0 used to be hosted on JCenter but isn't anymore.
I also think the project's build system with Gradle is at a 5.1.1 and hasn't been updated to a newer system.

Is there a way we can deprecate the package requirement?
Or retrofit the current build.gradle to build jda-nas from source?

**Comment by robinfriedli** [comment]
Do you use your own gradle installation or the supplied gradle wrapper? The wrapper should be Gradle 7.4.

Build failure is probably caused by this: https://status.gradle.com/incidents/9740r6bzx438

I'll look into moving away from jcenter completely as it's essentially deprecated but jda-nas isn't exactly actively maintained. Might migrate to https://github.com/MinnDevelopment/udpqueue.rs instead.

**Comment by irishgordo** [comment]
@robinfriedli  - thanks for the quick response back :smile: 
Ah, I was speaking in term's of jda-nas, I believe it's gradle wrapper was 5.1.1 - as I was trying to build it locally, when I wasn't able to fetch the dependency. 
Rust seems really great!

@robinfriedli ,
I happened to notice that the front-end off master, `src/main/webapp` was having some trouble with the `seed` dependency:
https://github.com/robinfriedli/aiode/blob/master/src/main/webapp/Cargo.toml#L14
At compile time - but I'm wondering if that issue is a Rust versioning issue perhaps?

I had no idea there was that gradle incident :sweat_smile:  - that totally makes sense - so I'll go ahead and close this out :+1:

**Comment by robinfriedli** [comment]
For the front-end build failure see #311 

I do love Rust, but I don't plan on working on the front-end any time soon
